version: '3'

services:
  jenkins:
    image: jenkins-with-docker
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    restart: always
    user: root 
    
volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
